name: Automerge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  set-auto-merge:
    name: Set Pull Request do Automerge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setting to Automerge
        uses: heitorpolidoro/automerge-pr@fail_if_not_enable
        with:
          fails_if_not_enabled: true
        env:
          heitrpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}
